# Generated by Django 5.2.1 on 2025-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
